name: test

on:
  push:
    branches:
      - 'feature/*'
      - 'features/*'
      - 'implement-feature/**'
      - 'implement-feature/**/**'
  pull_request:
    branches:
      - mainnet
      - testnet
      - 'feature/*'
      - 'features/*'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1 
        with:
          version: nightly-2b1f8d6dd90f9790faf0528e05e60e573a7569ce

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
